[[constraint]]
  name = "github.com/mmcdole/gofeed"
  branch = "master"

  source = "https://github.com/mmcdole/gofeed.git"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/shhj1998/rss-search-api"
  go-version = "1.12.6"
  install = ["./..."]

[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "1.3.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/google/logger"
  version = "1.0.1"
